src/Entity/Trip.php
<?php
/**
 * Created by PhpStorm.
 * User: M4rk0
 * Date: 7/25/2018
 * Time: 9:44 PM
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity
 * @ORM\Table(name="hc_trip")
 */
class Trip
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id_trip;
    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     * @Assert\Regex("/^.{3,}$/")
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="trips")
     * @ORM\JoinColumn(name="id_user", referencedColumnName="id_user")
     */
    private $user;

    /**
     * @return mixed
     */
    public function getIdTrip()
    {
        return $this->id_trip;
    }

    /**
     * @param mixed $id_trip
     */
    public function setIdTrip($id_trip): void
    {
        $this->id_trip = $id_trip;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void
    {
        $this->user = $user;
    }





}

templates/pages/gpx.html.twig
{% extends 'base-inside.html.twig' %}

{% block subbody %}

        <div class="row">
            <div class="col-lg-12">
                <div id="messagePlace">
                    {% if error_message is defined and error_message != null %}
                        <div class="alert alert-danger">{{ error_message }}</div>
                    {% endif %}
                    {% if success_message is defined and success_message != null %}
                        <div class="alert alert-success">{{ success_message }}</div>
                    {% endif %}
                </div>
                <form id="gpx-form" action="{{ path("page_gpx") }}" method="post" role="form" enctype="multipart/form-data">
                    <div class="form-group">
                        <input type="text" name="trip_name" id="trip_name" tabindex="1" class="form-control" placeholder="Trip name" value="" required>
                    </div>
                    <div class="form-group">
                        <input type="file" name="gpx_file" id="gpx_file" tabindex="2" required>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <input type="submit" name="submit" id="submit" tabindex="4" class="form-control btn btn-register" value="Upload">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    <script>
        // Attach a submit handler to the form
        $( "#gpx-form" ).submit(function( event ) {

            $("#submit").prop('disabled', true);;

        });
    </script>

{% endblock %}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="#" class="active" id="login-form-link">Login</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" id="register-form-link">Register</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div id="messagePlace">

                            </div>
                            <form id="login-form" method="post" role="form" style="display: block;">
                                <div class="form-group">
                                    <input type="email" name="_username" id="username" tabindex="1" class="form-control" placeholder="Email" value="{% if last_username is defined and last_username != null %}{{ last_username }}{% endif %}" required>
                                </div>
                                <div class="form-group">
                                    <input type="password" name="_password" id="password" tabindex="2" class="form-control" placeholder="Password" required>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <form id="register-form" action="{{ path("create_user") }}" method="post" role="form" style="display: none;">
                                <div class="form-group">
                                    <input type="email" name="rg_username" id="rg_username" tabindex="1" class="form-control" placeholder="Email" value="" required>
                                </div>
                                <div class="form-group">
                                    <input type="password" name="rg_password" id="rg_password" tabindex="2" class="form-control" placeholder="Password" required>
                                </div>
                                <div class="form-group">
                                    <input type="password" name="rg_confirm_password" id="rg_confirm_password" tabindex="2" class="form-control" placeholder="Confirm Password" required>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    {% if error_message is defined and error_message != null %}
        showErrorMessage("#messagePlace","{{ error_message }}");
    {% endif %}
    {% if success_message is defined and success_message != null %}
        showSuccessMessage("#messagePlace","{{ success_message }}");
    {% endif %}

    $(function() {

        $('#login-form-link').click(function(e) {
            openLoginForm();
            //e.preventDefault();
        });
        $('#register-form-link').click(function(e) {
            openRegistrationForm();
            //e.preventDefault();
        });

    });

    function openLoginForm() {
        $("#login-form").delay(100).fadeIn(100);
        $("#register-form").fadeOut(100);
        $('#register-form-link').removeClass('active');
        $('#login-form-link').addClass('active');
    }

    function openRegistrationForm() {
        $("#register-form").delay(100).fadeIn(100);
        $("#login-form").fadeOut(100);
        $('#login-form-link').removeClass('active');
        $('#register-form-link').addClass('active');
    }

    // Attach a submit handler to the form
    $( "#register-form" ).submit(function( event ) {

        // Stop form from submitting normally
        event.preventDefault();

        // Get some values from elements on the page:
        var $form = $( this ),
            url = $form.attr( "action" );

        var username = $("#rg_username");
        var password = $("#rg_password");
        var confirmPassword = $("#rg_confirm_password");

        if(!validatePassword(password.val())) {
            showErrorMessage("#messagePlace", "Password needs to contain minimum eight characters, at least one letter and one number.");
            return false;
        }

        if(!comparePasswords(password.val(), confirmPassword.val())) {
            showErrorMessage("#messagePlace", "Passwords don't match.");
            return false;
        }

        $.ajax({
            type: "POST",
            url: url,
            data: "username="+username.val()+"&password="+password.val(),
            success: function(data){
                showSuccessMessage("#messagePlace", data.message);
                openLoginForm();
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
                try {
                    var data = JSON.parse(XMLHttpRequest.responseText);
                    showErrorMessage("#messagePlace", data.message);
                } catch (e) {
                    showErrorMessage("#messagePlace", "Some error occured.");
                }
            }
        });

    });

    function showErrorMessage(divId, msg) {
        $(divId).html('<div class="alert alert-danger">'+msg+'</div>');
    }

    function showSuccessMessage(divId, msg) {
        $(divId).html('<div class="alert alert-success">'+msg+'</div>');
    }

    function validatePassword(password) {
        var patt = /(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[A-Za-z\d]{5,}$/;
        return patt.test(password);
    }

    function comparePasswords(pass1, pass2) {
        return pass1 === pass2;
    }
</script>

{% endblock %}

templates/pages/list.html.twig
{% extends 'base-inside.html.twig' %}

{% block subbody %}

    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-12">
                    <div id="map" style="width: 100%; height: 300px;"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <h5><b>Choose trip to display:</b></h5>
                    <div class="list-group">
                        {% for trip in trips %}
                            <li class="list-group-item list-group-item-action" style="cursor: pointer;" onclick="loadGPXFileIntoGoogleMap('{{ trip.idTrip }}')">{{ trip.name }}</li>
                        {% endfor %}
                        {% if trips|length <= 0 %}
                            No trips to display.
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyDRvCbo96siYMipmyXRd6aNdhFn0XIpRME"></script>
    <script src="{{ asset("js/loadgpx.js") }}"></script>
    <script>
        var map = null;

        function loadGPXFileIntoGoogleMap(idTrip) {
            if(map===null) {
                alert("Map is not initialized yet.");
                return;
            }
            $.ajax({url: "{{ path("gpx_file") }}?id_trip="+idTrip,
                dataType: "xml",
                success: function(data) {
                    var parser = new GPXParser(data, map);
                    parser.setTrackColour("#ed3274");     // Set the track line colour
                    parser.setTrackWidth(5);          // Set the track line width
                    parser.setMinTrackPointDelta(0.001);      // Set the minimum distance between track points
                    parser.centerAndZoom(data);
                    parser.addTrackpointsToMap();         // Add the trackpoints
                    parser.addRoutepointsToMap();         // Add the routepoints
                    parser.addWaypointsToMap();           // Add the waypoints
                }
            });
        }

        $(document).ready(function() {
            var mapOptions = {
                center: {lat: 31.280907, lng: -19.666702},
                zoom: 2,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map = new google.maps.Map(document.getElementById("map"),
                mapOptions);

        });




    </script>

{% endblock %}